import {randomUUID} from 'node:crypto';
import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {products as fallbackProducts, type Product} from '@/data/products';
import {COOKIE_NAME,verifySession} from '@/lib/rates-auth';
import {createAdminClient} from '@/lib/supabase/admin';

export const runtime='nodejs';
const allowedTypes=new Map([['image/jpeg','jpg'],['image/png','png'],['image/webp','webp']]);

async function authorized(){const store=await cookies();return verifySession(store.get(COOKIE_NAME)?.value)}
function unauthorized(){return NextResponse.json({error:'Unauthorized.'},{status:401})}
function text(form:FormData,key:string,max:number){const value=form.get(key);if(typeof value!=='string')throw new Error(`${key} is required.`);const clean=value.trim();if(!clean||clean.length>max)throw new Error(`Enter a valid ${key}.`);return clean}
function bool(form:FormData,key:string){return form.get(key)==='true'}
function productRow(product:Product){return {name:product.name,slug:product.slug,category:product.category,collection:product.collection,price:product.price,gold_purity:product.goldPurity,weight:product.weight,description:product.description,short_description:product.shortDescription,images:product.images.slice(0,2),featured:product.featured,trending:product.trending,new_arrival:product.newArrival,bridal:product.bridal,gender:product.gender,availability:product.availability,details:product.details,published:true}}
async function uploadImage(file:File){if(!allowedTypes.has(file.type)||file.size<=0||file.size>6*1024*1024)throw new Error('Each image must be JPG, PNG, or WebP and no larger than 6MB.');const path=`articles/${randomUUID()}.${allowedTypes.get(file.type)}`;const supabase=createAdminClient();const {error}=await supabase.storage.from('product-images').upload(path,file,{contentType:file.type,upsert:false});if(error)throw new Error(error.message);return supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl}

export async function GET(){if(!await authorized())return unauthorized();const {data,error}=await createAdminClient().from('products').select('*').order('id');return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({products:data})}

export async function POST(request:Request){if(!await authorized())return unauthorized();try{const type=request.headers.get('content-type')||'';if(type.includes('application/json')){const body=await request.json();if(body.action!=='import')throw new Error('Unsupported action.');const {data:existing,error:readError}=await createAdminClient().from('products').select('id').limit(1);if(readError)throw readError;if(existing?.length)return NextResponse.json({error:'Catalogue has already been imported.'},{status:409});const {error}=await createAdminClient().from('products').insert(fallbackProducts.map(productRow));if(error)throw error;return NextResponse.json({success:true,count:fallbackProducts.length})}
    const form=await request.formData();const files=form.getAll('images').filter((item):item is File=>item instanceof File&&item.size>0);if(files.length!==2)throw new Error('Exactly two product images are required.');const images=await Promise.all(files.map(uploadImage));const priceValue=form.get('price');const price=typeof priceValue==='string'&&priceValue.trim()?Number(priceValue):null;if(price!==null&&(!Number.isFinite(price)||price<=0))throw new Error('Enter a valid price or leave it empty.');const details=text(form,'details',500).split('\n').map(item=>item.trim()).filter(Boolean).slice(0,8);const row={name:text(form,'name',100),slug:text(form,'slug',100).toLowerCase(),category:text(form,'category',40),collection:text(form,'collection',60),price,gold_purity:text(form,'goldPurity',20),weight:text(form,'weight',80),description:text(form,'description',1000),short_description:text(form,'shortDescription',240),images,featured:bool(form,'featured'),trending:bool(form,'trending'),new_arrival:bool(form,'newArrival'),bridal:bool(form,'bridal'),gender:text(form,'gender',20),availability:text(form,'availability',40),details,published:bool(form,'published')};const {data,error}=await createAdminClient().from('products').insert(row).select().single();if(error)throw error;return NextResponse.json({product:data},{status:201})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to create article.'},{status:400})}}
