'use client';
import Image from 'next/image';
import Link from 'next/link';
import {Heart,X} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {formatPrice,Product} from '@/data/products';
import {business,messages,whatsappUrl} from '@/data/config';
import {useWishlist} from './wishlist-provider';
export function ProductCard({product}:{product:Product}){const[quick,setQuick]=useState(false);const{has,toggle}=useWishlist();return <article className="product"><Link className="product-visual" href={`/products/${product.slug}`}><Image src={product.images[0]} alt={product.name} fill sizes="(max-width: 700px) 100vw, 25vw"/><Image className="secondary" src={product.images[1]} alt={`${product.name}, alternate view`} fill sizes="(max-width: 700px) 100vw, 25vw"/><span>VIEW PIECE</span></Link><button className={`heart ${has(product.id)?'saved':''}`} aria-label={`${has(product.id)?'Remove':'Add'} ${product.name} ${has(product.id)?'from':'to'} wishlist`} onClick={()=>toggle(product.id)}><Heart size={17} fill={has(product.id)?'currentColor':'none'}/></button><button className="quick-trigger" onClick={()=>setQuick(true)}>QUICK VIEW</button><div className="product-info"><div><small>{product.category} · {product.goldPurity}</small><Link href={`/products/${product.slug}`}><h3>{product.name}</h3></Link></div><p>{formatPrice(product.price)}</p></div>{product.trending&&<em className="trend">Estimated interest · Popular today</em>}<QuickView product={product} open={quick} onClose={()=>setQuick(false)}/></article>}
function QuickView({product,open,onClose}:{product:Product;open:boolean;onClose:()=>void}){const close=useRef<HTMLButtonElement>(null);useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement|null;document.body.classList.add('locked');close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const modal=close.current?.closest('[role="dialog"]');const controls=modal?.querySelectorAll<HTMLElement>('button,a[href]');if(!controls?.length)return;const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};addEventListener('keydown',key);return()=>{removeEventListener('keydown',key);document.body.classList.remove('locked');previous?.focus()}},[open,onClose]);if(!open)return null;return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="quick-modal" role="dialog" aria-modal="true" aria-labelledby={`quick-${product.id}`}><button ref={close} className="modal-close" onClick={onClose} aria-label="Close quick view"><X/></button><div className="quick-image"><Image src={product.images[0]} alt={product.name} fill sizes="50vw"/></div><div className="quick-copy"><p className="eyebrow">{product.collection}</p><h2 id={`quick-${product.id}`}>{product.name}</h2><p className="quick-price">{formatPrice(product.price)}</p><dl><div><dt>Gold</dt><dd>{product.goldPurity}</dd></div><div><dt>Weight</dt><dd>{product.weight}</dd></div></dl><p>{product.shortDescription}</p>{business.whatsapp?<a className="btn gold" href={whatsappUrl(messages.product(product.name))}>Enquire on WhatsApp</a>:<p className="config-note">WhatsApp enquiry will be available when the business number is configured.</p>}<Link className="text-link" href={`/products/${product.slug}`}>View full product</Link></div></section></div>}
