'use client';
import Link from 'next/link';
import {FormEvent,useState} from 'react';
import {ArrowLeft,Lock,LogOut,Save} from 'lucide-react';
import type {LocalMarketRates} from '@/lib/metal-rates';
export function RatesDashboard({authenticated:initialAuth,configured,initialRates}:{authenticated:boolean;configured:boolean;initialRates:LocalMarketRates}){const[authenticated,setAuthenticated]=useState(initialAuth);const[error,setError]=useState('');if(!configured)return <DashboardFrame><div className="dashboard-message"><Lock/><h1>Dashboard setup required</h1><p>Add <code>RATES_ADMIN_PASSWORD</code> and <code>RATES_SESSION_SECRET</code> to the server environment before using this dashboard.</p></div></DashboardFrame>;if(!authenticated)return <Login onSuccess={()=>setAuthenticated(true)} error={error} setError={setError}/>;return <Editor initialRates={initialRates} onLogout={async()=>{await fetch('/api/rates-auth',{method:'DELETE'});setAuthenticated(false)}}/>}
function Login({onSuccess,error,setError}:{onSuccess:()=>void;error:string;setError:(v:string)=>void}){const[loading,setLoading]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError('');const form=new FormData(event.currentTarget);const response=await fetch('/api/rates-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:form.get('password')})});const body=await response.json();setLoading(false);if(!response.ok)return setError(body.error||'Unable to sign in.');onSuccess()}return <DashboardFrame><form className="dashboard-login" onSubmit={submit}><Lock/><p className="eyebrow">AUTHORIZED ACCESS</p><h1>MARKET RATES<br/><em>DASHBOARD</em></h1><label>Password<input name="password" type="password" autoComplete="current-password" required autoFocus/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn gold" disabled={loading}>{loading?'Signing in…':'Sign in'}</button></form></DashboardFrame>}
function Editor({initialRates,onLogout}:{initialRates:LocalMarketRates;onLogout:()=>void}){const[rates,setRates]=useState(initialRates);const[status,setStatus]=useState('');const[saving,setSaving]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setStatus('');const form=new FormData(event.currentTarget);const payload={gold24PerTola:form.get('gold24PerTola'),gold22PerTola:form.get('gold22PerTola'),silverPerTola:form.get('silverPerTola'),note:form.get('note')};const response=await fetch('/api/metal-rates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await response.json();setSaving(false);if(!response.ok)return setStatus(body.error||'Unable to save rates.');setRates(body.rates);setStatus('Rates saved and published to the website.')}return <DashboardFrame><div className="dashboard-toolbar"><div><p className="eyebrow">NAWABSHAH MARKET</p><h1>UPDATE RATES</h1></div><button onClick={onLogout}><LogOut size={16}/> Sign out</button></div><form className="rates-form" onSubmit={submit}><p>Enter current local market prices in Pakistani rupees per tola. Gram prices are calculated automatically.</p><div className="rate-inputs"><label>24K gold — PKR per tola<input name="gold24PerTola" type="number" min="1" max="100000000" step="1" required defaultValue={rates.gold24PerTola??''}/></label><label>22K gold — PKR per tola<input name="gold22PerTola" type="number" min="1" max="100000000" step="1" required defaultValue={rates.gold22PerTola??''}/></label><label>Silver — PKR per tola<input name="silverPerTola" type="number" min="1" max="100000000" step="1" required defaultValue={rates.silverPerTola??''}/></label></div><label>Optional market note<textarea name="note" maxLength={180} defaultValue={rates.note} placeholder="Example: Rates may change during the day."/></label>{status&&<p className={status.startsWith('Rates saved')?'form-success':'form-error'} role="status">{status}</p>}<button className="btn gold" disabled={saving}><Save size={16}/>{saving?'Saving…':'Save and publish'}</button></form></DashboardFrame>}
function DashboardFrame({children}:{children:React.ReactNode}){return <section className="dashboard-shell"><Link className="dashboard-back" href="/"><ArrowLeft size={15}/> Return to website</Link>{children}</section>}
