'use client';
import Link from 'next/link';
import {FormEvent,useState} from 'react';
import {ArrowLeft,Gem,Images,Lock,LogOut} from 'lucide-react';
import {ArticleManager} from './article-manager';
import {WebsiteImageManager} from './website-image-manager';
export function RatesDashboard({authenticated:initialAuth,configured}:{authenticated:boolean;configured:boolean}){const[authenticated,setAuthenticated]=useState(initialAuth);const[error,setError]=useState('');if(!configured)return <DashboardFrame><div className="dashboard-message"><Lock/><h1>Dashboard setup required</h1><p>Add <code>RATES_ADMIN_PASSWORD</code> and <code>RATES_SESSION_SECRET</code> to the server environment before using this dashboard.</p></div></DashboardFrame>;if(!authenticated)return <Login onSuccess={()=>setAuthenticated(true)} error={error} setError={setError}/>;return <Editor onLogout={async()=>{await fetch('/api/rates-auth',{method:'DELETE'});setAuthenticated(false)}}/>}
function Login({onSuccess,error,setError}:{onSuccess:()=>void;error:string;setError:(value:string)=>void}){const[loading,setLoading]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError('');const form=new FormData(event.currentTarget);const response=await fetch('/api/rates-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:form.get('password')})});const body=await response.json();setLoading(false);if(!response.ok)return setError(body.error||'Unable to sign in.');onSuccess()}return <DashboardFrame><form className="dashboard-login" onSubmit={submit}><Lock/><p className="eyebrow">AUTHORIZED ACCESS</p><h1>OWNER<br/><em>DASHBOARD</em></h1><label>Password<input name="password" type="password" autoComplete="current-password" required autoFocus/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn gold" disabled={loading}>{loading?'Signing in…':'Sign in'}</button></form></DashboardFrame>}
function Editor({onLogout}:{onLogout:()=>void}){const[tab,setTab]=useState<'articles'|'images'>('articles');return <DashboardFrame><div className="dashboard-toolbar"><div><p className="eyebrow">ZIA JEWELLERS</p><h1>OWNER DASHBOARD</h1></div><button onClick={onLogout}><LogOut size={16}/> Sign out</button></div><nav className="dashboard-tabs" aria-label="Dashboard sections"><button className={tab==='articles'?'active':''} onClick={()=>setTab('articles')}><Gem size={17}/> Articles</button><button className={tab==='images'?'active':''} onClick={()=>setTab('images')}><Images size={17}/> Website images</button></nav>{tab==='articles'?<ArticleManager/>:<WebsiteImageManager/>}</DashboardFrame>}
function DashboardFrame({children}:{children:React.ReactNode}){return <section className="dashboard-shell"><Link className="dashboard-back" href="/"><ArrowLeft size={15}/> Return to website</Link>{children}</section>}
