import {randomUUID} from 'node:crypto';
import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {COOKIE_NAME,verifySession} from '@/lib/rates-auth';
import {createAdminClient} from '@/lib/supabase/admin';

export const runtime='nodejs';
const types=new Map([['image/jpeg','jpg'],['image/png','png'],['image/webp','webp']]);
async function authorized(){const store=await cookies();return verifySession(store.get(COOKIE_NAME)?.value)}
async function upload(file:File,slot:string,variant:string){if(!types.has(file.type)||file.size<=0||file.size>10*1024*1024)throw new Error('Images must be JPG, PNG, or WebP and no larger than 10MB.');const path=`${slot}/${variant}-${randomUUID()}.${types.get(file.type)}`;const client=createAdminClient();const{error}=await client.storage.from('website-images').upload(path,file,{contentType:file.type});if(error)throw error;return client.storage.from('website-images').getPublicUrl(path).data.publicUrl}
async function remove(urls:(string|null)[]){const marker='/storage/v1/object/public/website-images/';const paths=urls.map(url=>{const index=url?.indexOf(marker)??-1;return index<0?null:decodeURIComponent(url!.slice(index+marker.length))}).filter((path):path is string=>Boolean(path));if(paths.length)await createAdminClient().storage.from('website-images').remove(paths)}
export async function GET(){if(!await authorized())return NextResponse.json({error:'Unauthorized.'},{status:401});const{data,error}=await createAdminClient().from('website_images').select('*').order('section').order('sort_order');return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({images:data})}
export async function PATCH(request:Request){if(!await authorized())return NextResponse.json({error:'Unauthorized.'},{status:401});try{const form=await request.formData();const slot=form.get('slot');if(typeof slot!=='string'||!/^[a-z0-9-]+$/.test(slot))throw new Error('Invalid image slot.');const client=createAdminClient();const{data:current,error:readError}=await client.from('website_images').select('*').eq('slot',slot).single();if(readError)throw readError;const desktop=form.get('desktop');const mobile=form.get('mobile');const desktopFile=desktop instanceof File&&desktop.size>0?desktop:null;const mobileFile=mobile instanceof File&&mobile.size>0?mobile:null;const imageUrl=desktopFile?await upload(desktopFile,slot,'desktop'):current.image_url;const mobileUrl=mobileFile?await upload(mobileFile,slot,'mobile'):form.get('removeMobile')==='true'?null:current.mobile_image_url;const alt=form.get('altText'),position=form.get('objectPosition');if(typeof alt!=='string'||alt.trim().length<2||alt.trim().length>180)throw new Error('Enter a useful image description.');if(typeof position!=='string'||position.trim().length<3||position.trim().length>40)throw new Error('Enter a valid focal position.');const{data,error}=await client.from('website_images').update({image_url:imageUrl,mobile_image_url:mobileUrl,alt_text:alt.trim(),object_position:position.trim(),updated_at:new Date().toISOString()}).eq('slot',slot).select().single();if(error){await remove([desktopFile?imageUrl:null,mobileFile?mobileUrl:null]);throw error}await remove([desktopFile?current.image_url:null,mobileFile||form.get('removeMobile')==='true'?current.mobile_image_url:null]);return NextResponse.json({image:data})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to update image.'},{status:400})}}
