create table public.products (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  category text not null,
  collection text not null,
  price numeric(12, 0) check (price is null or price > 0),
  gold_purity text not null,
  weight text not null,
  description text not null,
  short_description text not null,
  images text[] not null check (cardinality(images) = 2),
  featured boolean not null default false,
  trending boolean not null default false,
  new_arrival boolean not null default false,
  bridal boolean not null default false,
  gender text not null check (gender in ('Women', 'Men', 'Unisex')),
  availability text not null check (availability in ('Available to enquire', 'Made to order', 'Showroom exclusive')),
  details text[] not null default '{}',
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.market_rates (
  id smallint primary key default 1 check (id = 1),
  gold_24_per_tola numeric(12, 0) check (gold_24_per_tola is null or gold_24_per_tola > 0),
  gold_22_per_tola numeric(12, 0) check (gold_22_per_tola is null or gold_22_per_tola > 0),
  silver_per_tola numeric(12, 0) check (silver_per_tola is null or silver_per_tola > 0),
  note text not null default '' check (char_length(note) <= 180),
  updated_at timestamptz
);

insert into public.market_rates (id) values (1);

alter table public.products enable row level security;
alter table public.market_rates enable row level security;

revoke all on table public.products from anon, authenticated;
revoke all on table public.market_rates from anon, authenticated;
grant select on table public.products to anon, authenticated;
grant select on table public.market_rates to anon, authenticated;

create policy "Published products are publicly readable"
on public.products for select
to anon, authenticated
using (published = true);

create policy "Market rates are publicly readable"
on public.market_rates for select
to anon, authenticated
using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 6291456, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

revoke insert, update, delete on storage.objects from anon, authenticated;
